language: node_js

sudo: required

node_js: '10'

branches:
  only:
    - vuepress

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install

script:
  - npm run build
  - echo "yiukuenchu.me" > src/.vuepress/dist/CNAME # 这里 "chungzh.cn" 改成你自己的域名，如果没有，删掉这行就行了

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: src/.vuepress/dist
  name: $GIT_NAME
  email: $GIT_EMAIL
  keep-history: true
  target-branch: master
  on:
      branch: vuepress